name: weather_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  geolocator: ^5.2.0
  http: ^0.12.0+4
  font_awesome_flutter: ^8.5.0
  weather_icons: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
   - assets/
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/Font_awesome.otf
    - family: Avengers
      fonts:
        - asset: assets/Avengers.ttf
    - family: Horta
      fonts:
        - asset: assets/Horta.ttf

  uses-material-design: true

